# -*- coding: utf-8 -*-
"""JoesExpenseTracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAHBlZo5umS6gmlDtgWc-6h0qOn0S0ik
"""

print('Welcome to Joes Expense Tracker!\n \nPlease see below guide: \n - Enter your Monthly Budget \n - Enter the category of your expense \n - Enter the Cost \n - Enter "Exit" to see the final report \n - Enter "View to see an in progress report \n - Enter "Remove" to delete an entry \n')

while True:
  budget_input = input('What is your starting budget for this month? £').strip()
  try:
    budget = float(budget_input)
    break
  except ValueError:
    print('\nPlease enter a valid budget (numbers only).\n')
expenses = {}
while True:
  category = input('Enter Category of Expense: ').strip().title()
  if category == "Exit":
    break
  elif category == "View":
    print("\n--- Current Expense Log ---")
    if not expenses:
        print("(No expenses logged yet)")
    for item in expenses:
        item_cost = expenses[item]
        print(item + ": £" + f"{item_cost:.2f}")
    print("---------------------------")
    print("Remaining budget: £" + f"{budget:.2f}")
    print("---------------------------\n")
    continue
  elif category == "Remove":
    del_target = input("Which category would you like to remove? ").strip().title()
    if del_target not in expenses:
        print("\nThat category doesn't exist in your log.\n")
    else:
        budget = budget + expenses[del_target]
        del expenses[del_target]
        print("\nSuccessfully removed " + del_target + ". Money refunded!\n")
    continue
  else:
    while True:
      expense_cost = input('Enter the cost of ' + category + ': ').strip()
      try:
        cost = float(expense_cost)
        break
      except ValueError:
        print('\nPlease enter a valid number for the cost.\n')
    budget = budget - cost
    expenses[category] = cost

print("\n--- Final Expense Report ---")
for item in expenses:
    item_cost = expenses[item]
    print(item + ": £" + f"{item_cost:.2f}")

print("Final remaining balance: £" + f"{budget:.2f}")